# -*- coding: utf-8 -*-
"""loan predict.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mbMnMl-PRxbNqBJNT6jlMrtdEU_Po79g
"""

import pandas as pd
import numpy as np

train = pd.read_csv('/content/train.csv') 
train

train.isnull().sum()

train = train.dropna()
train.isnull().sum()

train.replace({'Gender':{'Male':0,'Female':1}},inplace=True)
train.replace({'Married':{'Yes':0,'No':1}},inplace=True)
train.replace({'Dependents':{'0':0,'1':1,'2':2,'3+':3}},inplace=True)
train.replace({'Education':{'Graduate':0,'Not Graduate':1}},inplace=True)
train.replace({'Self_Employed':{'Yes':0,'No':1}},inplace=True)
train.replace({'Property_Area':{'Rural':0,'Urban':1,'Semiurban':2}},inplace=True)
train.replace({'Income':{'low':0,'medium':1,'high':2}},inplace=True)
train.replace({'Application_Status':{'Y':0,'N':1}},inplace=True)

X = train[['Gender', 'Married', 'ApplicantIncome', 'LoanAmount', 'Credit_History']]
y = train.Loan_Status
X.shape, y.shape

from sklearn.model_selection import train_test_split
x_train, x_cv, y_train, y_cv = train_test_split(X,y, test_size = 0.2, random_state = 10)

from sklearn.ensemble import RandomForestClassifier 
model = RandomForestClassifier(max_depth=4, random_state = 10) 
model.fit(x_train, y_train)

from sklearn.metrics import accuracy_score
pred_cv = model.predict(x_cv)
accuracy_score(y_cv,pred_cv)

pred_train = model.predict(x_train)
accuracy_score(y_train,pred_train)

import pickle 
pickle_out = open("classifier.pkl", mode = "wb") 
pickle.dump(model, pickle_out) 
pickle_out.close()

